services:
  web:
    container_name: web
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot
    depends_on:
      - node
    networks:
      - network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - web
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot
    command: >
      certonly --webroot -w /var/www/certbot 
      --force-renewal 
      --email farhodov.b.m@gmail.com 
      --no-eff-email 
      -d farhodov.uz 
      -d www.farhodov.uz 
      --agree-tos

  node:
    image: node:22
    container_name: node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - network

networks:
  network:
    driver: bridge