services:
  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - network

  node:
    image: node:22
    container_name: node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - network

networks:
  network:
    driver: bridge