services:
  web:
    container_name: web
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    depends_on:
      - node
    networks:
      - network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - network

  node:
    image: node:22
    container_name: node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - network

volumes:
  www-certbot:
  etc-letsencrypt:

networks:
  network:
    driver: bridge